/* #ifndef ESFERA_H
#define ESFERA_H

 INICIAR_PARTIDA(){
 	COLOCAR_ESFERAS_EN_SU_ORIGEN();
 	SETEAR_VIDAS_EN_N();
 	RESETEAR_ULTI_A_PERSONAJES();

 RESTAR_VIDAS(*Esfera){
 	Esfera.vida= Esfera.vida -1;
 }

 HACER_APARECER_ULTI_EN_MAPA(posrandom){
 	COLOCAR_ULTI_EN_MAPA(posranmdom);
 }

 OBTENER_ULTI(*Esfera){
 	VERIFICAR_QUE_ESFERA_LA_OBTUVO();
 	DAR_ULTI(*ESFERA);
 }

 UTILIZAR_ULTI(*ESFERA){
 	//ESFERA HACE UN ULTI
 	RESETEAR_ULTI_A_PERSONAJE(*ESFERA);
 }

 REAPARECER_ESFERA(){
 	COLOCA_ESFERA_N_EN_ORIGEN();
 }



 }